# Generated by Django 2.0.2 on 2018-02-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=110, unique=True),
        ),
    ]
